// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/jorgen-simonsson/sotehus-backend"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/data": {
            "get": {
                "description": "Returns current status of grid consumption, electricity price, and solar production",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "energy"
                ],
                "summary": "Get current energy data",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.APIResponse"
                        }
                    }
                }
            }
        },
        "/api/energy/consumed": {
            "get": {
                "description": "Returns the energy consumed in kWh between two timestamps",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "energy"
                ],
                "summary": "Get consumed energy for a period",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start timestamp (RFC3339 format, e.g. 2026-02-01T00:00:00+01:00)",
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Stop timestamp (RFC3339 format, e.g. 2026-02-21T00:00:00+01:00)",
                        "name": "stop",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.EnergyConsumedResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid start/stop parameter",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to calculate energy consumption",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "InfluxDB not configured",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/energy/sold": {
            "get": {
                "description": "Returns the energy sold in kWh between two timestamps",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "energy"
                ],
                "summary": "Get sold energy for a period",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start timestamp (RFC3339 format, e.g. 2026-02-01T00:00:00+01:00)",
                        "name": "start",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Stop timestamp (RFC3339 format, e.g. 2026-02-21T00:00:00+01:00)",
                        "name": "stop",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.EnergySoldResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid start/stop parameter",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Failed to calculate energy sold",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "InfluxDB not configured",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/timeseries": {
            "get": {
                "description": "Returns statistics about the historical data stored in InfluxDB",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "energy"
                ],
                "summary": "Get time series statistics",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.TimeSeriesResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to query time series data",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "InfluxDB not configured",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/version": {
            "get": {
                "description": "Returns the current version of the API",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get API version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.VersionResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the health status of the API",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HealthResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.EnergyConsumedResponse": {
            "type": "object",
            "properties": {
                "actual_start": {
                    "type": "string",
                    "example": "2026-02-01T00:01:23+01:00"
                },
                "actual_stop": {
                    "type": "string",
                    "example": "2026-02-20T23:59:45+01:00"
                },
                "consumed": {
                    "type": "number",
                    "example": 523.45
                },
                "start": {
                    "type": "string",
                    "example": "2026-02-01T00:00:00+01:00"
                },
                "stop": {
                    "type": "string",
                    "example": "2026-02-21T00:00:00+01:00"
                },
                "unit": {
                    "type": "string",
                    "example": "kWh"
                }
            }
        },
        "api.EnergySoldResponse": {
            "type": "object",
            "properties": {
                "actual_start": {
                    "type": "string",
                    "example": "2026-02-01T00:01:23+01:00"
                },
                "actual_stop": {
                    "type": "string",
                    "example": "2026-02-20T23:59:45+01:00"
                },
                "sold": {
                    "type": "number",
                    "example": 123.45
                },
                "start": {
                    "type": "string",
                    "example": "2026-02-01T00:00:00+01:00"
                },
                "stop": {
                    "type": "string",
                    "example": "2026-02-21T00:00:00+01:00"
                },
                "unit": {
                    "type": "string",
                    "example": "kWh"
                }
            }
        },
        "api.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "api.TimeSeriesResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer",
                    "example": 523847
                },
                "first": {
                    "type": "string",
                    "example": "2025-11-01T16:10"
                },
                "last": {
                    "type": "string",
                    "example": "2025-12-07T16:30"
                }
            }
        },
        "api.VersionResponse": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "string",
                    "example": "1.2.0"
                }
            }
        },
        "models.APIResponse": {
            "type": "object",
            "properties": {
                "frequency": {
                    "$ref": "#/definitions/models.FrequencyData"
                },
                "grid": {
                    "$ref": "#/definitions/models.GridData"
                },
                "price": {
                    "$ref": "#/definitions/models.PriceData"
                },
                "solar": {
                    "$ref": "#/definitions/models.SolarData"
                }
            }
        },
        "models.FrequencyData": {
            "type": "object",
            "properties": {
                "frequency": {
                    "type": "number",
                    "example": 50.01
                },
                "lastUpdate": {
                    "type": "string",
                    "example": "2025-12-07T16:30:00+01:00"
                },
                "valid": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.GridData": {
            "type": "object",
            "properties": {
                "lastUpdate": {
                    "type": "string",
                    "example": "2025-12-07T16:30:00+01:00"
                },
                "message": {
                    "type": "string",
                    "example": ""
                },
                "power": {
                    "type": "number",
                    "example": 245.5
                },
                "valid": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.PriceData": {
            "type": "object",
            "properties": {
                "lastUpdate": {
                    "type": "string",
                    "example": "2025-12-07T16:15:00+01:00"
                },
                "price": {
                    "type": "number",
                    "example": 1.2
                },
                "valid": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "models.SolarData": {
            "type": "object",
            "properties": {
                "lastUpdate": {
                    "type": "string",
                    "example": "2025-12-07T15:00:00+01:00"
                },
                "message": {
                    "type": "string",
                    "example": "No sun"
                },
                "power": {
                    "type": "number",
                    "example": 0
                },
                "valid": {
                    "type": "boolean",
                    "example": false
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Sotehus Backend API",
	Description:      "Real-time energy monitoring API providing grid consumption, electricity price, and solar production data.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
